name = "Coffees Aero SMP"
version = "1.8.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87cea6f6869897a8c3bc3972d1e0cff1f8b64256248229c43c8cfbb2d0a8a030"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4"]
datapack-folder = "overrides/datapacks"
