name = "Coffees Aero SMP"
version = "1.7.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31c158b86778a2b2a1ee0da30f33882a5b288ce262446ca3b9f3e5336ec5b231"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4"]
datapack-folder = "overrides/datapacks"
