name = "Coffees Aero SMP"
version = "1.10.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de60ba0ff7a7836cd79db4ea04c69b9f33b9fb1cb2b814e08c47eacaf8eb61be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"

[options]
acceptable-game-versions = ["1.21", "1.21.1", "1.21.2", "1.21.3", "1.21.4"]
datapack-folder = "overrides/datapacks"
