modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved (c) 2026 MrCoffeeBench"

[[mods]]
modId       = "coffees_aero_auth"
version     = "${file.jarVersion}"
displayName = "Coffees Aero Auth"
authors     = "MrCoffeeBench"
credits     = "Coffees Aero SMP"
logoFile    = "logo.png"
description = '''
Authentication and profile system for Coffees Aero SMP public server.
Supports Mojang-authenticated (premium) and offline (cracked) players.
Profiles are UUID-bound. Display names are globally unique and anti-spoof protected.
'''

[[mixins]]
config = "coffeesaeroauth.mixins.json"

[[dependencies.coffees_aero_auth]]
    modId        = "neoforge"
    type         = "required"
    versionRange = "[21.1,)"
    ordering     = "NONE"
    side         = "BOTH"

[[dependencies.coffees_aero_auth]]
    modId        = "minecraft"
    type         = "required"
    versionRange = "[1.21.1,1.22)"
    ordering     = "NONE"
    side         = "BOTH"
