name = "Coffees Aero SMP Season 3"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6940cb35a7a80a9ae10f40813716e22a8bc993a6536f7a070a4bc4a18f4c279b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
