name = "Coffees Aero SMP Season 3"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "999f46c5bd65d0547ebde68294ee87923fffeaf7090581bf1222592ecdccd16e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
