modLoader="javafml"
loaderVersion="[21,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''
Core client-side mod for Coffees Aero SMP.
Manages the custom main menu, server auto-connect, and admin access control.
'''

[[dependencies.coffeesaerosmp_core]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.coffeesaerosmp_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="CLIENT"
